### ISSUE TITLE
add hover color effect on cart option

### ISSUE THREAD

**Issue by GitWiz01** [GitWiz01/Project-D-W#2]
Simply use the hover property in CSS and change the color of the cart option to green when someone hovers the mouse over it

The color should change to success green of bootstrap color themes

Good luck!

**Comment by Judah1604** [comment]
hey can i help fix the issue

**Comment by GitWiz01** [comment]
Issue assigned to you, proceed to work. Also after the issue gets resolved do attach a video with a live demo.
Have a good day 👍🏼

**Comment by Judah1604** [comment]
Sorry, I mistakenly clicked unassign me. Please assign me back.

**Comment by GitWiz01** [comment]
Done, You can start working now

**Comment by Judah1604** [comment]
### Issue #2 Add hover color effect on cart option

Demo
[contribution-1.webm](https://user-images.githubusercontent.com/81442563/229309714-8bc24d49-0669-41e5-b510-38c830a310ce.webm)

Changed the cart text color to bootstrap success green color.

**Comment by GitWiz01** [comment]
Great @Judah1604 go ahead with a PR
