### ISSUE TITLE
Website Design Not Responsive 

### ISSUE THREAD

**Issue by rahulrana701** [GitWiz01/Project-D-W#9]
The website is not responsive , it is getting distorted at various widths, it is not rendering properly on phones....
<br>
<div style="display:flex "> <img  width="377" height="324" alt="Screenshot 2023-04-14 121406" src="https://user-images.githubusercontent.com/123585591/231965369-953b7858-bfdf-4cf6-8f1b-87217129eaa2.png"> 
<img width="367" alt="Screenshot 2023-04-14 121436" src="https://user-images.githubusercontent.com/123585591/231965386-6786504f-527e-4948-81fc-8b5b8f8ca2b2.png"></div>

**Comment by rahulrana701** [comment]
hey @GitWiz01 If you want , I can work on this issue....

**Comment by rahulrana701** [comment]
@GitWiz01 are you still maintaining this project............

**Comment by Aaditiyakansal** [comment]
> @GitWiz01 are you still maintaining this project.......... 
He is but kind a busy right now , we will be glad if u work on it

**Comment by rahulrana701** [comment]
Ok .........

**Comment by GitWiz01** [comment]
@RahulRana701 I have assigned you the issue, you can start working on it 👍🏼

**Comment by rahulrana701** [comment]
hey @GitWiz01 I have created a pr regarding this issue, hope it has solved the issue.....https://github.com/GitWiz01/Project-D-W/pull/10#issue-1670163387

**Comment by GitWiz01** [comment]
Thanks for contributing. Your pr looks good to me will merge it shortly.

**Comment by rahulrana701** [comment]
thanks @GitWiz01 can you suggest me some more projects where I can contribute

**Comment by GitWiz01** [comment]
@RahulRana701  Check out https://goodfirstissue.dev/
